receivers:
  prometheus/example-program:
    trim_metric_suffixes: true
    config:
      scrape_configs:
      - job_name: example-program
        scrape_interval: 5s
        #metric_name_validation_scheme: legacy
        #fallback_scrape_protocol: PrometheusText0.0.4
        static_configs:
        - targets:
          - example-program:2223

processors:
  filter/example-program:
    metrics:
      include:
        match_type: strict
        metric_names:
        - metric_counter
        - metric.counter

exporters:
  debug:
    verbosity: detailed

  file:
    path: /logs/metrics.json

service:
  pipelines:
    metrics:
      receivers:
      - prometheus/example-program
      processors:
      - filter/example-program
      exporters:
      - debug
  telemetry:
    logs:
      level: debug
      output_paths: ["/logs/otel.log"]